### ISSUE TITLE
js not available on unpkg.com (404)

### ISSUE THREAD

**Issue by sdementen** [BusinessOptics/dash_interactive_graphviz#1]
the source refers to the js file
https://unpkg.com/dash_interactive_graphviz@0.0.3/dash_interactive_graphviz/dash_interactive_graphviz.min.js which returns a 404.
Same fo the js.map file

**Comment by JHSaunders** [comment]
Hi,

I have not packaged this properly on NPM. You can use it by setting serve_locally=True (which should be the default). I have to wait 24 hours to publish it again on NPM (because I did something stupid). I will bump the version and do that tomorrow.

**Comment by JHSaunders** [comment]
@sdementen Please update to version 0.1.1 I have correctly packaged it for NPM and everything should work.
