### ISSUE TITLE
Engine used by d3-graphviz

### ISSUE THREAD

**Issue by INNOVINATI** [BusinessOptics/dash_interactive_graphviz#2]
Hi,

this component is a great solution for a little open-source project we just started. Everything works fine, but we cannot get d3-graphviz to change the generated layout.
Now, we have forked this repo and played around directly in the source code, but there's no effect when adding `.graphviz().engine("neato")`  or any other supported engine. The graph is always in tree layout, but we need it to be circular/star-shaped, since we have a lot of nodes connecting to a single root node. Do you have any idea, why this is not working or what we could do to fix it?

Thanks in advance!

**Comment by JHSaunders** [comment]
Hmmm, I had not thought of that, I can dive in and have a look over the
weekend.
--
James Saunders
Founder/CTO

www.businessoptics.biz
james@businessoptics.biz
+27 79 770 9290

**Comment by JHSaunders** [comment]
Hey,

Please have a look at https://github.com/BusinessOptics/dash_interactive_graphviz/pull/3, I stupidly lost some work but I think this should do what you want. Let me know and I can merge it.

I hope the lock down in germany is going OK for you.

**Comment by INNOVINATI** [comment]
Hi James,

thanks for getting back to us so quickly. The lockdown has impacted us in positive manner so far, since we get to stay in pyjamas while coding :-)

The attached commit looks good so far, I think that should be exactly what we need. I'll try out later tonight/tomorrow and will give you feedback here. Thanks again!

Cheers,
Max

**Comment by INNOVINATI** [comment]
So I just took a closer look at it, looks great! Closing this thread - thanks James!
